name: Build on push (OpenShift)
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install oc
        run: |
          curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz \
          | tar -xz oc && sudo mv oc /usr/local/bin/
      - name: Login
        run: |
          oc login "https://api.rm2.thpm.p1.openshiftapps.com:6443" \
            --token="eyJhbGciOiJSUzI1NiIsImtpZCI6Ik44bmJtRDBQX3AwVG9JMm1rSVZBZUNScHdjbVRfUzM3cGR3RXJwZnFibjQifQ.eyJhdWQiOlsiaHR0cHM6Ly9vaWRjLm9wMS5vcGVuc2hpZnRhcHBzLmNvbS8yZmVnZ2V2bDRnbThoa2MxZXNuN3VkcXY2ZW9qcTRpaCJdLCJleHAiOjE3NTU0NTEyNjAsImlhdCI6MTc1NTAxOTI2MCwiaXNzIjoiaHR0cHM6Ly9vaWRjLm9wMS5vcGVuc2hpZnRhcHBzLmNvbS8yZmVnZ2V2bDRnbThoa2MxZXNuN3VkcXY2ZW9qcTRpaCIsImp0aSI6IjBjZTQxY2JmLTE3MjktNDI1Mi1iMTA5LWRhMjJlMWEwNTgzNiIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoicmRvbGRhbi1kZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiY2ktYm90IiwidWlkIjoiYWQ0YWE1OTUtMzcyOS00ZTM0LTk3MzktM2I2YTE3ZTZkMzA5In19LCJuYmYiOjE3NTUwMTkyNjAsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpyZG9sZGFuLWRldjpjaS1ib3QifQ.WFru8HLcxzVxGlYZKTUsb-RQSHhT23zPCikqWx22yMyy8BH-x04NfbRnXZiwyYOh48nJh0M1UbKVM8z1cvTYdWdbVEUbzoqe83ik_wq2SONtA3b-S1nq-yi-_UQPAVXVk_TJmTVj46gWUdQcxeh5ZeEzCEHOWX98pj5RiXmtr1ZPlx3H63Zu7mk3OWyMvEO7tMLTa1ceyKCtQqbWXlHKHsELi9lrca1s7IX6z2HQZhM3pQq2CLioLIINfd_48ojTAmMVcbn4FVscima5ojOeYz47Tmqm0mPIEoG-3Z0neuNkE4N6URjMWVt0IR4ocFQTw644lsWj-i5mwCV2SHAqx1LBeYHgJFSgRu4OOFdYt1_ZXqoGQK-qtMC18XNKmTWE9NwTaTrEmGxMNg7Xjbj5E5zsfLftYu9G8fJjHhj9RUUF8Kx0Dyb-aasg9ascC-j5URBCU9PMefcQY05dExntZkFCI5DPkGvN19ue_TLMm2ziVabIntu61Oa97U1yH8awUwdoXCiCAzrf_jIQPd7DBuQH1nDP2ly4fNGaJq50RcL3I0hoog9nbTVe3zdQ5Nj04rYsDaZWQfChW6fCxr0jWwOpxECbwZn5JBd4nqyZcKgEBNv232BOLieIp1gl6sMJdGldTopT6rLi-s6Nb_I6nXzAcG5Owv--ALpOuRRQ3VM" \
            --insecure-skip-tls-verify=true
          oc project rdoldan-dev
      - name: Trigger build
        run: |
          oc start-build web-s2i --wait --follow
